# Generated by Django 5.2.3 on 2025-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JOB_Type',
            field=models.CharField(choices=[('Full TIME', 'Full TIME'), ('PART TIME', 'PART TIME')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
